### ISSUE TITLE
Add Gujarati and Marathi

### ISSUE THREAD

**Issue by sumitgohil** [ncpierson/google-tts-languages#8]
Hi, Can you please add Gujarati and Marathi. Language code for the same is

Gujarati : gu-IN
Marathi : mr-IN
Malayalam : ml-IN
Kannada : kn-IN

Also, is it possible to add different voice as mentioned in the official cloud docs. 

https://cloud.google.com/text-to-speech/docs/voices

**Comment by ncpierson** [comment]
Hi @sumitgohil ,

This repository is not for voices from the Google Cloud TTS service. You can get those by making a [web request](https://cloud.google.com/text-to-speech/docs/reference/rest/v1/voices/list).

This repo is exclusively for tracking the undocumented list of voices supported by translate.google.com. There is a large overlap, but it's not the same thing.

However, the voices you suggested have recently gained support on translate.google.com, so I added them to this repo and are available in `v1.0.2`.

**Comment by ncpierson** [comment]
I tend to pair this project (`google-tts-language`) with this other js library for fetching tts clips:

https://github.com/zlargon/google-tts
